### ISSUE TITLE
USDCAD/2016/27...39 result in ERROR 404: Not Found.

### ISSUE THREAD

**Issue by marshray** [FXCMAPI/FXCMTickData#1]
Thank you all for making this great data available!

URLs
https://tickdata.fxcorporate.com/USDCAD/2016/27.csv.gz through https://tickdata.fxcorporate.com/USDCAD/2016/39.csv.gz are 404.

It's been like this for at least a week.

E.g.,
$ wget https://tickdata.fxcorporate.com/USDCAD/2016/27.csv.gz
--2017-02-11 14:06:18--  https://tickdata.fxcorporate.com/USDCAD/2016/27.csv.gz
Resolving tickdata.fxcorporate.com (tickdata.fxcorporate.com)... 69.164.13.145
Connecting to tickdata.fxcorporate.com (tickdata.fxcorporate.com)|69.164.13.145|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-02-11 14:06:18 ERROR 404: Not Found.

Thanks again!

**Comment by FXCMAPI** [comment]
Hello Marsh

We are working on it, will update you shortly

Best regards
Lei

**Comment by FXCMAPI** [comment]
Hello Marsh

This has been fixed.

Please let me know if you have any questions

Best regards
Lei

**Comment by marshray** [comment]
Confirmed fixed.
Thanks again!
- Marsh
