### ISSUE TITLE
Tick data URLs missing

### ISSUE THREAD

**Issue by Ulidan** [FXCMAPI/FXCMTickData#2]
HI,

Following URLs are missing:
[https://tickdata.fxcorporate.com/AUDJPY/2016/37.csv.gz](https://tickdata.fxcorporate.com/AUDJPY/2016/37.csv.gz)
[https://tickdata.fxcorporate.com/AUDJPY/2016/38.csv.gz](https://tickdata.fxcorporate.com/AUDJPY/2016/38.csv.gz)
[https://tickdata.fxcorporate.com/AUDJPY/2016/39.csv.gz](https://tickdata.fxcorporate.com/AUDJPY/2016/39.csv.gz)

All the rest are great.
Thanks
Ulidan

**Comment by FXCMAPI** [comment]
Hello Elia

It is there now.

Thanks
Lei

**Comment by Ulidan** [comment]
Great,
Thanks
