### ISSUE TITLE
Missing data

### ISSUE THREAD

**Issue by jpeg729** [FXCMAPI/FXCMTickData#5]
Files for EURJPY 2016 weeks 36, 37, 38 and 39 are empty of data. 
They contain only the header line, but nothing more.

**Comment by FXCMAPI** [comment]
We are working on it

Thanks
Lei

**Comment by jpeg729** [comment]
Same for 

AUDNZD 2017 week 29
CADCHF 2017 week 29
GBPNZD 2017 week 29
NZDCAD 2017 week 29
NZDCHF 2017 week 29

**Comment by FXCMAPI** [comment]
Should be good now

Thanks
Lei

**Comment by FXCMAPI** [comment]
Should be good now

Thanks
Lei

**Comment by FXCMAPI** [comment]
upload the correct file.

**Comment by FXCMAPI** [comment]
upload the correct file.
